# comment
a (# comment #) a
a ab a56b $xx_67 _67A a78$ZZ
+ +- <=>
1 1.12 1E+2 1.2E+5 0FF#16
"string" "string\"string" "string $"
$"string" $"string\$string"
$"string$( $"string \$ \" string $(
)$ string $( )$ string \$ \" string $(
)$ string " )$ string \$ \" string "
\\ zig string
\\ zig string $ \
; ( ) . , + - * / & == != < <= => > := : => { }
div mod rem not and or pass exit next return when unless if then elsif else end begin
while loop for in do

a+b a+1 1+1
